/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author HOME
 */
public class Ciudades extends javax.swing.JInternalFrame {

    /**
     * Creates new form CIUDAD
     */
    public Ciudades() {
        initComponents();
        setTitle("Ciudad");
        setSize(570, 458);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etidescripcion = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelciudad = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        eticiudad = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciudad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(40, 20, 50, 15);

        etidescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidescripcion.setText("Descripcion:");
        jPanel1.add(etidescripcion);
        etidescripcion.setBounds(10, 50, 70, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(90, 20, 80, 20);
        jPanel1.add(txtdescripcion);
        txtdescripcion.setBounds(90, 50, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 50, 456, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelciudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelciudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(panelciudad);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 14, 480, 140);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(16, 168, 500, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jButton1.setText("Nuevo");
        jPanel3.add(jButton1);
        jButton1.setBounds(2, 2, 63, 23);

        jButton2.setText("Guardar");
        jPanel3.add(jButton2);
        jButton2.setBounds(79, 2, 71, 23);

        jButton3.setText("Modificar");
        jPanel3.add(jButton3);
        jButton3.setBounds(156, 2, 75, 23);

        jButton4.setText("Borrar");
        jPanel3.add(jButton4);
        jButton4.setBounds(241, 2, 63, 23);

        jButton5.setText("Vista");
        jPanel3.add(jButton5);
        jButton5.setBounds(320, 2, 55, 23);

        jButton6.setText("Salir");
        jPanel3.add(jButton6);
        jButton6.setBounds(381, 2, 53, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 279, 456, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel4.add(btnnuevo);
        btnnuevo.setBounds(10, 20, 70, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel4.add(btnguardar);
        btnguardar.setBounds(90, 20, 80, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel4.add(btnmodificar);
        btnmodificar.setBounds(180, 20, 90, 23);

        btnborrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnborrar.setText("Borrar");
        jPanel4.add(btnborrar);
        btnborrar.setBounds(280, 20, 67, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel4.add(btncancelar);
        btncancelar.setBounds(360, 20, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel4.add(btnvista);
        btnvista.setBounds(460, 20, 59, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 350, 530, 60);

        eticiudad.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        eticiudad.setText("Ciudades");
        getContentPane().add(eticiudad);
        eticiudad.setBounds(220, 20, 120, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JLabel eticiudad;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etidescripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelciudad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
