/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author HOME
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CLIENTE
     */
    public Cliente() {
        initComponents();
        setTitle("Cliente");
        setSize(763, 529);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etiCI = new javax.swing.JLabel();
        etinombre = new javax.swing.JLabel();
        eticompania = new javax.swing.JLabel();
        etidireccion = new javax.swing.JLabel();
        eticiudad = new javax.swing.JLabel();
        etitelefono = new javax.swing.JLabel();
        etiemail = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcompania = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        combonacionalidad = new javax.swing.JComboBox();
        txttelefono = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        etiapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        etinacionalidad = new javax.swing.JLabel();
        etitipodedocumento = new javax.swing.JLabel();
        etidepartamento = new javax.swing.JLabel();
        combociudad = new javax.swing.JComboBox();
        combodepartamento = new javax.swing.JComboBox();
        combotipodedocumento = new javax.swing.JComboBox();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelcliente = new javax.swing.JTable();
        eticliente = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setText("Nº Cliente");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 16, 48, 14);

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(42, 63, 37, 14);

        jLabel4.setText("Compañia");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(32, 99, 47, 14);

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(36, 127, 43, 14);

        jLabel6.setText("Ciudad");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(46, 152, 33, 14);

        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(37, 184, 42, 14);

        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(55, 219, 24, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(182, 13, 31, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(182, 65, 128, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(182, 96, 128, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(182, 121, 128, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(182, 146, 128, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(106, 178, 204, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(106, 216, 204, 20);

        jLabel15.setText("CI:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(42, 42, 15, 14);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(182, 39, 128, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(26, 40, 0, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Datos para factura (Editable)");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 13, 199, 17);

        jLabel11.setText("Nombre");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 51, 37, 14);

        jLabel12.setText("Domicilio");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 77, 40, 14);

        jLabel13.setText("Ciudad");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 103, 33, 14);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(74, 48, 68, 20);
        jPanel2.add(jTextField10);
        jTextField10.setBounds(74, 74, 68, 20);
        jPanel2.add(jTextField11);
        jTextField11.setBounds(73, 100, 69, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(26, 372, 0, 0);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel3.add(eticodigo);
        eticodigo.setBounds(10, 30, 60, 15);

        etiCI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiCI.setText("CI.:");
        jPanel3.add(etiCI);
        etiCI.setBounds(150, 30, 18, 15);

        etinombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etinombre.setText("Nombre:");
        jPanel3.add(etinombre);
        etinombre.setBounds(200, 70, 60, 15);

        eticompania.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticompania.setText("Compania:");
        jPanel3.add(eticompania);
        eticompania.setBounds(180, 190, 61, 15);

        etidireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidireccion.setText("Direccion:");
        jPanel3.add(etidireccion);
        etidireccion.setBounds(190, 130, 60, 20);

        eticiudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticiudad.setText("Ciudad:");
        jPanel3.add(eticiudad);
        eticiudad.setBounds(500, 80, 43, 15);

        etitelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitelefono.setText("Telefono:");
        jPanel3.add(etitelefono);
        etitelefono.setBounds(190, 160, 51, 15);

        etiemail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiemail.setText("Email:");
        jPanel3.add(etiemail);
        etiemail.setBounds(200, 220, 35, 15);

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        jPanel3.add(txtcodigo);
        txtcodigo.setBounds(60, 30, 80, 20);

        txtCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIActionPerformed(evt);
            }
        });
        jPanel3.add(txtCI);
        txtCI.setBounds(190, 30, 80, 20);
        jPanel3.add(txtnombre);
        txtnombre.setBounds(250, 70, 200, 20);

        txtcompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompaniaActionPerformed(evt);
            }
        });
        jPanel3.add(txtcompania);
        txtcompania.setBounds(250, 190, 200, 20);
        jPanel3.add(txtdireccion);
        txtdireccion.setBounds(250, 130, 200, 20);

        jPanel3.add(combonacionalidad);
        combonacionalidad.setBounds(560, 50, 80, 20);
        jPanel3.add(txttelefono);
        txttelefono.setBounds(250, 160, 200, 20);
        jPanel3.add(txtemail);
        txtemail.setBounds(250, 220, 200, 20);

        etiapellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiapellido.setText("Apellido:");
        jPanel3.add(etiapellido);
        etiapellido.setBounds(200, 100, 50, 15);
        jPanel3.add(txtapellido);
        txtapellido.setBounds(250, 100, 200, 20);

        etinacionalidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etinacionalidad.setText("Nacionalidad:");
        jPanel3.add(etinacionalidad);
        etinacionalidad.setBounds(470, 50, 76, 15);

        etitipodedocumento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitipodedocumento.setText("Tipo de Documento:");
        jPanel3.add(etitipodedocumento);
        etitipodedocumento.setBounds(440, 20, 120, 15);

        etidepartamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidepartamento.setText("Departamento:");
        jPanel3.add(etidepartamento);
        etidepartamento.setBounds(470, 110, 90, 15);

        jPanel3.add(combociudad);
        combociudad.setBounds(560, 80, 80, 20);

        jPanel3.add(combodepartamento);
        combodepartamento.setBounds(560, 110, 80, 20);

        combotipodedocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipodedocumentoActionPerformed(evt);
            }
        });
        jPanel3.add(combotipodedocumento);
        combotipodedocumento.setBounds(560, 20, 80, 20);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 80, 90, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnguardar);
        btnguardar.setBounds(10, 110, 90, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(10, 140, 90, 23);

        btneliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar);
        btneliminar.setBounds(10, 170, 90, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(10, 200, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel3.add(btnvista);
        btnvista.setBounds(10, 230, 90, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(50, 50, 680, 260);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        panelcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CI", "Nombre", "Apellido", "Direccion", "Telefono", "Compañia", "Email", "Tipo de documento", "Nacionalidad", "Ciudad", "Departamento"
            }
        ));
        jScrollPane1.setViewportView(panelcliente);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 710, 130);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 330, 730, 150);

        eticliente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        eticliente.setText("Cliente");
        getContentPane().add(eticliente);
        eticliente.setBounds(290, 20, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void combotipodedocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipodedocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipodedocumentoActionPerformed

    private void txtCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIActionPerformed

    private void txtcompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompañiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompañiaActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JComboBox combociudad;
    private javax.swing.JComboBox combodepartamento;
    private javax.swing.JComboBox combonacionalidad;
    private javax.swing.JComboBox combotipodedocumento;
    private javax.swing.JLabel etiCI;
    private javax.swing.JLabel etiapellido;
    private javax.swing.JLabel eticiudad;
    private javax.swing.JLabel eticliente;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel eticompania;
    private javax.swing.JLabel etidepartamento;
    private javax.swing.JLabel etidireccion;
    private javax.swing.JLabel etiemail;
    private javax.swing.JLabel etinacionalidad;
    private javax.swing.JLabel etinombre;
    private javax.swing.JLabel etitelefono;
    private javax.swing.JLabel etitipodedocumento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable panelcliente;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcompania;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
