/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import control.E_Control.Control_Formas_de_Pago;
import modelo.Entidades.Entidad_Formas_de_Pago;

/**
 *
 * @author jose
 */
public class Formas_de_Pagooo extends javax.swing.JInternalFrame implements ActionListener {
			Entidad_Formas_de_Pago entF=new Entidad_Formas_de_Pago();
			Control_Formas_de_Pago contF=new Control_Formas_de_Pago();
    /**
     * Creates new form Formas_de_Pago
     */
    public Formas_de_Pagooo() {
        initComponents();
        setSize(601, 420);
        setTitle("Formas de Pago");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
        mostrardatosdetabla();
    }
    private void mostrardatosdetabla() {
		// TODO Auto-generated method stub
    	DefaultTableModel modelo =new DefaultTableModel(){
    		@Override
    		public boolean isCellEditable(int filas,int columna){
    			if (columna==1){
    				return true;
    			}else{
    				return false;
    			}
    			
    		}
    	};
		
    	panelformasdepago.setModel(modelo);
		modelo.addColumn("Codigo");
		modelo.addColumn("Descripcion");
		
		panelformasdepago.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
		panelformasdepago.getTableHeader().setReorderingAllowed(false);
		
		contF.tablamodelo(modelo);
		jScrollPane1.setViewportView(panelformasdepago);
		panelformasdepago.addMouseListener(new MouseAdapter() { 	
				 
			  public void mouseClicked(MouseEvent e)
			  {
			  int seleccion = panelformasdepago.rowAtPoint(e.getPoint());
			  txtcodigo.setText(String.valueOf(panelformasdepago.getValueAt(seleccion, 0)));
			
			  txtdescripcion.setText(String.valueOf(panelformasdepago.getValueAt(seleccion, 1)));
			  
				btnmodificar.setEnabled(true);
				btneliminar.setEnabled(true);
			
				txtdescripcion.requestFocus();
				txtdescripcion.setEnabled(true);
				btnnuevo.setEnabled(false);
				btnvista.setEnabled(true);
				btnguardar.setEnabled(false);
				txtcodigo.setVisible(true);
				eticodigo.setVisible(true);
			  }
			  });
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etidescripcion = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        etiformasdepago = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelformasdepago = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(40, 20, 50, 15);
        eticodigo.setVisible(false);

        etidescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etidescripcion.setText("Descripcion:");
        jPanel1.add(etidescripcion);
        etidescripcion.setBounds(20, 50, 80, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(100, 20, 80, 20);
        txtcodigo.setEnabled(false);
        txtcodigo.setVisible(false);
        jPanel1.add(txtdescripcion);
        txtdescripcion.setBounds(100, 50, 120, 20);
        txtdescripcion.setEnabled(false);
        
        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 40, 510, 120);

        etiformasdepago.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiformasdepago.setText("Formas de Pago");
        getContentPane().add(etiformasdepago);
        etiformasdepago.setBounds(190, 10, 200, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 480, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 170, 510, 130);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnnuevo.setToolTipText("Agregar Registro ");
      //  btnvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Agregar.png")));
        btnvista.setIcon(new ImageIcon(getClass().getResource("/imag/add.png")));
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 10,  40, 40);
        btnnuevo.addActionListener(this);
        
        btnguardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnguardar.setToolTipText("Guardar Datos");
        btnvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/save.png")));
        jPanel3.add(btnguardar);
        btnguardar.setBounds(70, 10, 40, 40);
        btnguardar.addActionListener(this);
        btnguardar.setEnabled(false);

        btnmodificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnmodificar.setToolTipText("Modificar Registro");
        btnvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/update.png")));
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(130, 10, 40, 40);
        btnmodificar.setEnabled(false);
        btnmodificar.addActionListener(this);

        btneliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btneliminar.setToolTipText("Eliminar Registro");
        btnvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Delete.png")));
        jPanel3.add(btneliminar);
        btneliminar.setBounds(190, 10, 40, 40);
        btneliminar.setEnabled(false);
        btneliminar.addActionListener(this);

       btncancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btncancelar.setToolTipText("Cancelar Operacion");
        btncancelar.setText("Cancelar");
        btnvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Cancel.png")));
        jPanel3.add(btncancelar);
        btncancelar.setBounds(270, 10, 40, 40);
        btncancelar.addActionListener(this);

        btnvista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnvista.setToolTipText("Crear Reporte");
        btnvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Vista.png")));
        jPanel3.add(btnvista);
        btnvista.setBounds(340, 10, 40, 40);
        btnvista.setEnabled(false);
        btnvista.addActionListener(this);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 310, 550, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etidescripcion;
    private javax.swing.JLabel etiformasdepago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelformasdepago;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		if(e.getSource()==btnnuevo){
			habilitarcampos();
		}
		if(e.getSource()==btnguardar){
			Registrar();
		}
		if(e.getSource()==btnmodificar){
			Modificar();
		}
		if(e.getSource()==btneliminar){
			Eliminar();
		}
		if(e.getSource()==btncancelar){
			LimpiarCampo();
		}
		if(e.getSource()==btnvista){
			Vista();
		}
		
	}

	private void Vista() {
		// TODO Auto-generated method stub
		
	}

	private void LimpiarCampo() {
		// TODO Auto-generated method stub
		txtdescripcion.setEnabled(false);
    	txtcodigo.setText("");
		txtdescripcion.setText("");
		
		btnguardar.setEnabled(false);
		btnmodificar.setEnabled(false);
		btneliminar.setEnabled(false);
		btnvista.setEnabled(false);
		btnnuevo.setEnabled(true);
		eticodigo.setVisible(false);
		txtcodigo.setVisible(false);
		
	}


	private void Eliminar() {
		// TODO Auto-generated method stub
		int opcion=JOptionPane.showConfirmDialog(this,"Desea Eliminar Registro", null,JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
		
		if(opcion==0){
			entF.setIdFormas_de_Pago(Integer.parseInt(txtcodigo.getText().trim()));
			entF.setDescripcion(txtdescripcion.getText());
			contF.eliminar(entF);
			
		}
		mostrardatosdetabla();
		
	}

	private void Modificar() {
		// TODO Auto-generated method stub
		int reg=JOptionPane.showConfirmDialog(this, "Desea Modificar Registro", null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		if(reg==0){
			entF.setIdFormas_de_Pago(Integer.parseInt(txtcodigo.getText().trim()));
			entF.setDescripcion(txtdescripcion.getText());
			contF.modificar(entF);
		}
		mostrardatosdetabla();
		
	}

	private void Registrar() {
		// TODO Auto-generated method stub
		int reg=JOptionPane.showConfirmDialog(this, "Desea Guardar Datos", null,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
		//JOptionPane.showMessageDialog(null, "La Opcion es "+ reg);
		if(reg==0){
			entF.setDescripcion(txtdescripcion.getText().trim());
			contF.registrar(entF);
			
		}
		mostrardatosdetabla();
	}

	private void habilitarcampos() {
		// TODO Auto-generated method stub
		txtdescripcion.setEnabled(true);
		txtdescripcion.setText("");
		txtdescripcion.requestFocus();
		btnguardar.setEnabled(true);
		
	}
	
}
