/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author jose
 */
public class Modelo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Modelo
     */
    public Modelo() {
        initComponents();
        setTitle("Modelo");
        setSize(636, 446);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etidescripcion = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        combomodelo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        etimodelo = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(100, 20, 50, 15);

        etidescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidescripcion.setText("Descripcion:");
        jPanel1.add(etidescripcion);
        etidescripcion.setBounds(80, 50, 70, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(160, 20, 90, 20);
        jPanel1.add(txtdescripcion);
        txtdescripcion.setBounds(160, 50, 160, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 40, 470, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        combomodelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        combomodelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(combomodelo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(12, 20, 500, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 150, 530, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 20, 73, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel3.add(btnguardar);
        btnguardar.setBounds(90, 20, 80, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(180, 20, 81, 23);

        btneliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        jPanel3.add(btneliminar);
        btneliminar.setBounds(270, 20, 80, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(360, 20, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel3.add(btnvista);
        btnvista.setBounds(460, 20, 59, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 330, 530, 50);

        etimodelo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etimodelo.setText("Modelo");
        getContentPane().add(etimodelo);
        etimodelo.setBounds(270, 10, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JTable combomodelo;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etidescripcion;
    private javax.swing.JLabel etimodelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
