/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author HOME
 */
public class Servicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TALLER
     */
    public Servicios() {
        initComponents();
        setTitle("Servicios");
        setSize(588, 498);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etinombredelservicio = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombredelservicio = new javax.swing.JTextField();
        etitipodeservicio = new javax.swing.JLabel();
        combotipodeservicio = new javax.swing.JComboBox();
        eticostodeservicio = new javax.swing.JLabel();
        txtcostodelservicio = new javax.swing.JTextField();
        etiIVA = new javax.swing.JLabel();
        comboIVA = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelservicio = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        etiservicio = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servicios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(10, 20, 43, 15);

        etinombredelservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etinombredelservicio.setText("Nombre del Servicio:");
        jPanel1.add(etinombredelservicio);
        etinombredelservicio.setBounds(170, 20, 114, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(60, 20, 70, 20);
        jPanel1.add(txtnombredelservicio);
        txtnombredelservicio.setBounds(290, 20, 170, 20);

        etitipodeservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitipodeservicio.setText("Tipo de Servicio:");
        jPanel1.add(etitipodeservicio);
        etitipodeservicio.setBounds(10, 130, 100, 15);

        combotipodeservicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suspencion", "Parte Electrica" }));
        jPanel1.add(combotipodeservicio);
        combotipodeservicio.setBounds(110, 130, 80, 20);

        eticostodeservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticostodeservicio.setText("Costo de Servicio:");
        jPanel1.add(eticostodeservicio);
        eticostodeservicio.setBounds(180, 50, 100, 15);

        txtcostodelservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostodelservicioActionPerformed(evt);
            }
        });
        jPanel1.add(txtcostodelservicio);
        txtcostodelservicio.setBounds(290, 50, 170, 20);

        etiIVA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiIVA.setText("IVA:");
        jPanel1.add(etiIVA);
        etiIVA.setBounds(340, 130, 20, 15);

        jPanel1.add(comboIVA);
        comboIVA.setBounds(380, 130, 80, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 60, 510, 160);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jButton1.setText("Nuevo");
        jPanel3.add(jButton1);
        jButton1.setBounds(2, 13, 63, 23);

        jButton2.setText("Guardar");
        jPanel3.add(jButton2);
        jButton2.setBounds(71, 13, 71, 23);

        jButton3.setText("Modificar");
        jPanel3.add(jButton3);
        jButton3.setBounds(148, 13, 75, 23);

        jButton4.setText("Borrar");
        jPanel3.add(jButton4);
        jButton4.setBounds(229, 13, 63, 23);

        jButton5.setText("Vista");
        jPanel3.add(jButton5);
        jButton5.setBounds(306, 13, 55, 23);

        jButton6.setText("Salir");
        jPanel3.add(jButton6);
        jButton6.setBounds(371, 13, 53, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 390, 466, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelservicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre del Servicio", "IVA", "Tipo de Servicio"
            }
        ));
        jScrollPane1.setViewportView(panelservicio);
        panelservicio.getColumnModel().getColumn(1).setResizable(false);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 520, 140);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 230, 540, 160);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnnuevo);
        btnnuevo.setBounds(0, 10, 80, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnguardar);
        btnguardar.setBounds(90, 10, 80, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel4.add(btnmodificar);
        btnmodificar.setBounds(180, 10, 90, 23);

        btnborrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnborrar.setText("Borrar");
        jPanel4.add(btnborrar);
        btnborrar.setBounds(280, 10, 80, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel4.add(btncancelar);
        btncancelar.setBounds(370, 10, 83, 23);

        btnvista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel4.add(btnvista);
        btnvista.setBounds(470, 10, 61, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 400, 540, 50);

        etiservicio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiservicio.setText("Servicios");
        getContentPane().add(etiservicio);
        etiservicio.setBounds(230, 20, 120, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtcostodelservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostodelservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostodelservicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JComboBox comboIVA;
    private javax.swing.JComboBox combotipodeservicio;
    private javax.swing.JLabel etiIVA;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel eticostodeservicio;
    private javax.swing.JLabel etinombredelservicio;
    private javax.swing.JLabel etiservicio;
    private javax.swing.JLabel etitipodeservicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelservicio;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcostodelservicio;
    private javax.swing.JTextField txtnombredelservicio;
    // End of variables declaration//GEN-END:variables
}
