/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author jose
 */
public class Tipo_de_Documento extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public Tipo_de_Documento() {
        initComponents();
        setTitle("Tipo de Documento");
        setSize(583, 439);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneltipodedocumento = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etitipo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        etitipodedocumento = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 155, 0, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        paneltipodedocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(paneltipodedocumento);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(12, 10, 480, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 180, 500, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel3.add(eticodigo);
        eticodigo.setBounds(30, 20, 50, 15);

        etitipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitipo.setText("Tipo:");
        jPanel3.add(etitipo);
        etitipo.setBounds(40, 60, 27, 15);
        jPanel3.add(txtcodigo);
        txtcodigo.setBounds(80, 20, 60, 20);
        jPanel3.add(txttipo);
        txttipo.setBounds(80, 60, 180, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 70, 480, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel4.add(btnnuevo);
        btnnuevo.setBounds(10, 10, 80, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel4.add(btnguardar);
        btnguardar.setBounds(100, 10, 80, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel4.add(btnmodificar);
        btnmodificar.setBounds(190, 10, 90, 23);

        btneliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        jPanel4.add(btneliminar);
        btneliminar.setBounds(290, 10, 80, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel4.add(btncancelar);
        btncancelar.setBounds(380, 10, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel4.add(btnvista);
        btnvista.setBounds(480, 10, 59, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 340, 550, 50);

        etitipodedocumento.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etitipodedocumento.setText("Tipo de Documento");
        getContentPane().add(etitipodedocumento);
        etitipodedocumento.setBounds(200, 30, 230, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etitipo;
    private javax.swing.JLabel etitipodedocumento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paneltipodedocumento;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
