/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author HOME
 */
public class Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        setTitle("Usuario");
        setSize(664, 490);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etinombre = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        etidireccion = new javax.swing.JLabel();
        etitelefono = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        etiapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelusuario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        etiusuario = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(10, 20, 50, 15);

        etinombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etinombre.setText("Nombre:");
        jPanel1.add(etinombre);
        etinombre.setBounds(170, 10, 50, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(60, 20, 70, 20);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(220, 10, 220, 20);

        etidireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidireccion.setText("Direccion:");
        jPanel1.add(etidireccion);
        etidireccion.setBounds(160, 70, 70, 15);

        etitelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitelefono.setText("Telefono:");
        jPanel1.add(etitelefono);
        etitelefono.setBounds(160, 100, 60, 15);
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(220, 70, 220, 20);

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txttelefono);
        txttelefono.setBounds(220, 100, 220, 20);

        etiapellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiapellido.setText("Apellido:");
        jPanel1.add(etiapellido);
        etiapellido.setBounds(170, 40, 47, 15);
        jPanel1.add(txtapellido);
        txtapellido.setBounds(220, 40, 220, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 600, 150);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelusuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(panelusuario);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 570, 150);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 200, 590, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 20, 67, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnguardar);
        btnguardar.setBounds(100, 20, 77, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(190, 20, 90, 23);

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);
        btnEliminar.setBounds(290, 20, 80, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar);
        btncancelar.setBounds(380, 20, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel3.add(btnvista);
        btnvista.setBounds(480, 20, 59, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 390, 570, 60);

        etiusuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiusuario.setText("Usuario");
        getContentPane().add(etiusuario);
        etiusuario.setBounds(270, 10, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JLabel etiapellido;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etidireccion;
    private javax.swing.JLabel etinombre;
    private javax.swing.JLabel etitelefono;
    private javax.swing.JLabel etiusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelusuario;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
