/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Referencial;

/**
 *
 * @author jose
 */
public class Vehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vehiculo
     */
    public Vehiculo() {
        initComponents();
        setTitle("Vehiculo");
        setSize(600, 500);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelvehiculo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        eticliente = new javax.swing.JLabel();
        etichasis = new javax.swing.JLabel();
        etiplaca = new javax.swing.JLabel();
        etimarca = new javax.swing.JLabel();
        etimodelo = new javax.swing.JLabel();
        combomarca = new javax.swing.JComboBox();
        combomodelo = new javax.swing.JComboBox();
        txtcliente = new javax.swing.JTextField();
        txtchasis = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        btnvista = new javax.swing.JButton();
        etivehiculo = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 11, 0, 0);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, -190, 452, 110);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, -160, 452, 160);

        panelvehiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelvehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Chasis", "Placa", "Marca", "Modelo"
            }
        ));
        jScrollPane3.setViewportView(panelvehiculo);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 490, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 280, 510, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setLayout(null);

        eticodigo.setText("Codigo:");
        jPanel3.add(eticodigo);
        eticodigo.setBounds(16, 28, 40, 14);

        eticliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticliente.setText("Cliente:");
        jPanel3.add(eticliente);
        eticliente.setBounds(170, 40, 50, 15);

        etichasis.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etichasis.setText("Chasis:");
        jPanel3.add(etichasis);
        etichasis.setBounds(170, 70, 50, 15);

        etiplaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiplaca.setText("Placa:");
        jPanel3.add(etiplaca);
        etiplaca.setBounds(180, 100, 40, 15);

        etimarca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etimarca.setText("Marca:");
        jPanel3.add(etimarca);
        etimarca.setBounds(180, 130, 40, 15);

        etimodelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etimodelo.setText("Modelo:");
        jPanel3.add(etimodelo);
        etimodelo.setBounds(180, 160, 50, 15);

        jPanel3.add(combomarca);
        combomarca.setBounds(230, 130, 110, 20);

        jPanel3.add(combomodelo);
        combomodelo.setBounds(230, 160, 110, 20);
        jPanel3.add(txtcliente);
        txtcliente.setBounds(230, 40, 220, 20);
        jPanel3.add(txtchasis);
        txtchasis.setBounds(230, 70, 220, 20);
        jPanel3.add(txtplaca);
        txtplaca.setBounds(230, 100, 220, 20);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 60, 90, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel3.add(btnguardar);
        btnguardar.setBounds(10, 90, 90, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(10, 120, 90, 23);

        btneliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        jPanel3.add(btneliminar);
        btneliminar.setBounds(10, 150, 90, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(10, 180, 90, 23);
        jPanel3.add(txtcodigo);
        txtcodigo.setBounds(60, 30, 80, 20);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel3.add(btnvista);
        btnvista.setBounds(10, 210, 90, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 30, 530, 240);

        etivehiculo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etivehiculo.setText("Vehiculo");
        getContentPane().add(etivehiculo);
        etivehiculo.setBounds(220, 0, 120, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JComboBox combomarca;
    private javax.swing.JComboBox combomodelo;
    private javax.swing.JLabel etichasis;
    private javax.swing.JLabel eticliente;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etimarca;
    private javax.swing.JLabel etimodelo;
    private javax.swing.JLabel etiplaca;
    private javax.swing.JLabel etivehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable panelvehiculo;
    private javax.swing.JTextField txtchasis;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
