/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Refereciales;

import java.awt.image.ImagingOpException;

import javax.swing.ImageIcon;

/**
 *
 * @author jose
 */
public class Formas_de_Pago extends javax.swing.JInternalFrame {

    /**
     * Creates new form Formas_de_Pago
     */
    public Formas_de_Pago() {
        initComponents();
        setSize(617, 473);
        setTitle("Formas de Pago");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etidescripcion = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        etiformasdepago = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelformasdepago = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(40, 20, 50, 15);

        etidescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etidescripcion.setText("Descripcion:");
        jPanel1.add(etidescripcion);
        etidescripcion.setBounds(20, 50, 80, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(100, 20, 80, 20);
        jPanel1.add(txtdescripcion);
        txtdescripcion.setBounds(100, 50, 120, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 40, 510, 120);

        etiformasdepago.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiformasdepago.setText("Formas de Pago");
        getContentPane().add(etiformasdepago);
        etiformasdepago.setBounds(190, 10, 200, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelformasdepago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        panelformasdepago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelformasdepagoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(panelformasdepago);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 480, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 170, 510, 130);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnnuevo.setToolTipText("Agregar Registro");
        btnmodificar.setIcon(new ImageIcon(getClass().getResource("/imag/Nuevo.png")));
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 10, 70, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnguardar.setToolTipText("Guardar Datos");
        btnmodificar.setIcon(new ImageIcon(getClass().getResource("/imag/Save.png")));
        jPanel3.add(btnguardar);
        btnguardar.setBounds(90, 10, 79, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnmodificar.setToolTipText("Modificar Registro");
        btnmodificar.setIcon(new ImageIcon(getClass().getResource("/imag/Update.png")));
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(180, 10, 90, 23);

        btneliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btneliminar.setToolTipText("Eliminar Registro");
        btnmodificar.setIcon(new ImageIcon(getClass().getResource("/imag/Delete.png")));
        jPanel3.add(btneliminar);
        btneliminar.setBounds(280, 10, 80, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btncancelar.setToolTipText("Cancelar Operacion");
        btnmodificar.setIcon(new ImageIcon(getClass().getResource("/imag/Cancel.png")));
        jPanel3.add(btncancelar);
        btncancelar.setBounds(370, 10, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnvista.setToolTipText("Crear Reportes");
        btnmodificar.setIcon(new ImageIcon(getClass().getResource("/imag/Vista.png")));
        jPanel3.add(btnvista);
        btnvista.setBounds(470, 10, 70, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 310, 550, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelformasdepagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelformasdepagoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelformasdepagoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etidescripcion;
    private javax.swing.JLabel etiformasdepago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelformasdepago;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
