/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Informes;

/**
 *
 * @author jose
 */
public class Consulta_Agenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Agenda
     */
    public Consulta_Agenda() {
        initComponents();
        setTitle("Consulta Agenda");
        setSize(815, 508);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiselecciona_una_opcion = new javax.swing.JLabel();
        jRadioButtoncodigo = new javax.swing.JRadioButton();
        jRadioButtonnumero_de_documento = new javax.swing.JRadioButton();
        combocodigo = new javax.swing.JComboBox();
        txtnumero_de_documento = new javax.swing.JTextField();
        btnver_cliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        eticonsulta_agenda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelconsulta_agenda = new javax.swing.JTable();
        etibuscar_cliente = new javax.swing.JLabel();
        txtbuscar_cliente = new javax.swing.JTextField();
        btnvistas = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 510));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        etiselecciona_una_opcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiselecciona_una_opcion.setText("Selecciona una opcion:");
        jPanel1.add(etiselecciona_una_opcion);
        etiselecciona_una_opcion.setBounds(20, 20, 130, 15);

        buttonGroup1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtoncodigo.setText("Estado");
        jPanel1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setBounds(20, 50, 65, 23);

        buttonGroup1.add(jRadioButtonnumero_de_documento);
        jRadioButtonnumero_de_documento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonnumero_de_documento.setText("Numero de Documento");
        jPanel1.add(jRadioButtonnumero_de_documento);
        jRadioButtonnumero_de_documento.setBounds(250, 50, 160, 23);

        combocodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combocodigo);
        combocodigo.setBounds(20, 80, 170, 20);
        jPanel1.add(txtnumero_de_documento);
        txtnumero_de_documento.setBounds(250, 80, 210, 20);

        btnver_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnver_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/repo.png"))); // NOI18N
        btnver_cliente.setText("Ver Registros");
        jPanel1.add(btnver_cliente);
        btnver_cliente.setBounds(610, 130, 140, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/0025-search.gif"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 130, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 770, 170);

        eticonsulta_agenda.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        eticonsulta_agenda.setText("Consulta Agenda");
        getContentPane().add(eticonsulta_agenda);
        eticonsulta_agenda.setBounds(300, 10, 190, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        panelconsulta_agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CI", "Nombre", "Apellido", "Fecha de Inicio", "Fecha Final"
            }
        ));
        jScrollPane1.setViewportView(panelconsulta_agenda);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 750, 110);

        etibuscar_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etibuscar_cliente.setText("Buscar Cliente:");
        jPanel2.add(etibuscar_cliente);
        etibuscar_cliente.setBounds(20, 20, 90, 15);
        jPanel2.add(txtbuscar_cliente);
        txtbuscar_cliente.setBounds(110, 20, 400, 20);

        btnvistas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/netbeans-ide-icono-8962-32.png"))); // NOI18N
        btnvistas.setText("Vista");
        jPanel2.add(btnvistas);
        btnvistas.setBounds(520, 10, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 220, 770, 200);

        btnagregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/agregar.gif"))); // NOI18N
        btnagregar.setText("Agregar");
        getContentPane().add(btnagregar);
        btnagregar.setBounds(170, 430, 110, 30);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/dibujo-a-lapiz-modificar-escribir-icono-8118-32.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        getContentPane().add(btnmodificar);
        btnmodificar.setBounds(300, 430, 117, 30);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancelar-icono-4624-32.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar);
        btncancelar.setBounds(440, 430, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnver_cliente;
    private javax.swing.JButton btnvistas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox combocodigo;
    private javax.swing.JLabel etibuscar_cliente;
    private javax.swing.JLabel eticonsulta_agenda;
    private javax.swing.JLabel etiselecciona_una_opcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtoncodigo;
    private javax.swing.JRadioButton jRadioButtonnumero_de_documento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelconsulta_agenda;
    private javax.swing.JTextField txtbuscar_cliente;
    private javax.swing.JTextField txtnumero_de_documento;
    // End of variables declaration//GEN-END:variables
}
