/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Informes;

/**
 *
 * @author jose
 */
public class Consulta_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Cliente
     */
    public Consulta_Cliente() {
        initComponents();
        setSize(779, 490);
        setTitle("Consulta de Cliente");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Etiselecione_una_opcion = new javax.swing.JLabel();
        jRadioButtoncodigo = new javax.swing.JRadioButton();
        jRadioButtonnumerodedocumento = new javax.swing.JRadioButton();
        txtnumero_de_Documento = new javax.swing.JTextField();
        btnvercliente = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        etibuscarcliente = new javax.swing.JLabel();
        txtbuscar_cliente = new javax.swing.JTextField();
        btnvistas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta_cliente = new javax.swing.JTable();
        eticonsulta_cliente = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(780, 530));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        Etiselecione_una_opcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Etiselecione_una_opcion.setText("Seleccione una opcion:");
        jPanel1.add(Etiselecione_una_opcion);
        Etiselecione_una_opcion.setBounds(12, 13, 130, 15);

        buttonGroup1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtoncodigo.setText("Codigo");
        jPanel1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setBounds(40, 30, 65, 23);

        buttonGroup1.add(jRadioButtonnumerodedocumento);
        jRadioButtonnumerodedocumento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonnumerodedocumento.setText("Numero de Documento");
        jPanel1.add(jRadioButtonnumerodedocumento);
        jRadioButtonnumerodedocumento.setBounds(260, 30, 160, 23);
        jPanel1.add(txtnumero_de_Documento);
        txtnumero_de_Documento.setBounds(250, 60, 210, 20);

        btnvercliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvercliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/repo.png"))); // NOI18N
        btnvercliente.setText("Ver Registros");
        jPanel1.add(btnvercliente);
        btnvercliente.setBounds(570, 110, 140, 33);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 60, 190, 20);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/0025-search.gif"))); // NOI18N
        jButton1.setText("Buscar");
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 110, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 740, 150);

        jPanel2.setLayout(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 11, 660, 140);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 170, 650, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(null);

        etibuscarcliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etibuscarcliente.setText("Buscar Cliente:");
        jPanel4.add(etibuscarcliente);
        etibuscarcliente.setBounds(12, 13, 90, 15);
        jPanel4.add(txtbuscar_cliente);
        txtbuscar_cliente.setBounds(110, 10, 380, 20);

        btnvistas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/netbeans-ide-icono-8962-32.png"))); // NOI18N
        btnvistas.setText("Vista");
        jPanel4.add(btnvistas);
        btnvistas.setBounds(500, 10, 95, 30);

        tablaconsulta_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CI", "Nombre", "Apellido", "Marca", "Modelo", "Placa"
            }
        ));
        jScrollPane1.setViewportView(tablaconsulta_cliente);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 720, 120);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 200, 740, 190);

        eticonsulta_cliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        eticonsulta_cliente.setText("Consulta Cliente");
        getContentPane().add(eticonsulta_cliente);
        eticonsulta_cliente.setBounds(260, 10, 220, 29);

        btnagregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/agregar.gif"))); // NOI18N
        btnagregar.setText("Agregar");
        getContentPane().add(btnagregar);
        btnagregar.setBounds(160, 410, 99, 30);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/dibujo-a-lapiz-modificar-escribir-icono-8118-32.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        getContentPane().add(btnmodificar);
        btnmodificar.setBounds(270, 410, 120, 30);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancelar-icono-4624-32.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar);
        btncancelar.setBounds(400, 410, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiselecione_una_opcion;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnvercliente;
    private javax.swing.JButton btnvistas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etibuscarcliente;
    private javax.swing.JLabel eticonsulta_cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtoncodigo;
    private javax.swing.JRadioButton jRadioButtonnumerodedocumento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaconsulta_cliente;
    private javax.swing.JTextField txtbuscar_cliente;
    private javax.swing.JTextField txtnumero_de_Documento;
    // End of variables declaration//GEN-END:variables
}
