/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Informes;

/**
 *
 * @author jose
 */
public class Consulta_Orden_de_Trabajo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Servicios
     */
    public Consulta_Orden_de_Trabajo() {
        initComponents();
        setSize(773, 521);
        setTitle("Consulta Orden de Trabajo");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiseleccione_una_opcion = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 530));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        etiseleccione_una_opcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiseleccione_una_opcion.setText("Seleccione una opcion:");
        jPanel1.add(etiseleccione_una_opcion);
        etiseleccione_una_opcion.setBounds(20, 30, 130, 15);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setText("Codigo");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(30, 60, 80, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton2.setText("Numero de Documento");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(250, 60, 155, 23);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 90, 190, 20);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/repo.png"))); // NOI18N
        jButton1.setText("Ver Registro");
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 140, 130, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 90, 190, 20);

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/0025-search.gif"))); // NOI18N
        jButton6.setText("Buscar");
        jPanel1.add(jButton6);
        jButton6.setBounds(430, 140, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 700, 180);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha", "Servicio", "Cantidad", "Cliente"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 640, 130);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Buscar Cliente:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 15);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(100, 20, 370, 20);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/netbeans-ide-icono-8962-32.png"))); // NOI18N
        jButton2.setText("Vista");
        jPanel2.add(jButton2);
        jButton2.setBounds(500, 20, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 240, 700, 200);

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/agregar.gif"))); // NOI18N
        jButton3.setText("Agregar");
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 450, 100, 29);

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/dibujo-a-lapiz-modificar-escribir-icono-8118-32.png"))); // NOI18N
        jButton4.setText("Modificar");
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 450, 117, 30);

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancelar-icono-4624-32.png"))); // NOI18N
        jButton5.setText("Cancelar");
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 450, 119, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Consulta de Orden de Trabajo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 10, 340, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel etiseleccione_una_opcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
