/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Informes;

/**
 *
 * @author jose
 */
public class Consulta_Empleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Empleado
     */
    public Consulta_Empleado() {
        initComponents();
        setTitle("Consulta Empleado");
        setSize(753, 501);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiselecciona_una_opcion = new javax.swing.JLabel();
        jRadioButtoncodigo = new javax.swing.JRadioButton();
        jRadioButtonnumero_de_documento = new javax.swing.JRadioButton();
        txtnumero_de_documento = new javax.swing.JTextField();
        btnver_cliente = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        eticonsulta_Empleado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panleconsulta_empleado = new javax.swing.JTable();
        etibuscar_cliente = new javax.swing.JLabel();
        txtbuscar_cliente = new javax.swing.JTextField();
        btnvistas = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 530));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        etiselecciona_una_opcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiselecciona_una_opcion.setText("Selecciona una opcion:");
        jPanel1.add(etiselecciona_una_opcion);
        etiselecciona_una_opcion.setBounds(20, 20, 130, 15);

        buttonGroup1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtoncodigo.setText("Codigo");
        jPanel1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setBounds(20, 40, 65, 23);

        buttonGroup1.add(jRadioButtonnumero_de_documento);
        jRadioButtonnumero_de_documento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonnumero_de_documento.setText("Numero de Documento");
        jPanel1.add(jRadioButtonnumero_de_documento);
        jRadioButtonnumero_de_documento.setBounds(210, 40, 160, 23);
        jPanel1.add(txtnumero_de_documento);
        txtnumero_de_documento.setBounds(210, 70, 190, 20);

        btnver_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnver_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/repo.png"))); // NOI18N
        btnver_cliente.setText("Ver Registro");
        jPanel1.add(btnver_cliente);
        btnver_cliente.setBounds(560, 150, 130, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 70, 180, 20);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/0025-search.gif"))); // NOI18N
        jButton1.setText("Buscar");
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 150, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 710, 190);

        eticonsulta_Empleado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        eticonsulta_Empleado.setText("Consulta Empleado");
        getContentPane().add(eticonsulta_Empleado);
        eticonsulta_Empleado.setBounds(250, 10, 220, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        panleconsulta_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Direccion", "Descripcion", "Telefono", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(panleconsulta_empleado);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 690, 110);

        etibuscar_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etibuscar_cliente.setText("Buscar Cliente:");
        jPanel2.add(etibuscar_cliente);
        etibuscar_cliente.setBounds(20, 10, 90, 15);
        jPanel2.add(txtbuscar_cliente);
        txtbuscar_cliente.setBounds(110, 10, 390, 20);

        btnvistas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/netbeans-ide-icono-8962-32.png"))); // NOI18N
        btnvistas.setText("Vista");
        jPanel2.add(btnvistas);
        btnvistas.setBounds(520, 10, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 240, 710, 170);

        btnagregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/agregar.gif"))); // NOI18N
        btnagregar.setText("Agregar");
        getContentPane().add(btnagregar);
        btnagregar.setBounds(220, 430, 100, 30);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/dibujo-a-lapiz-modificar-escribir-icono-8118-32.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar);
        btnmodificar.setBounds(330, 430, 120, 30);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancelar-icono-4624-32.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar);
        btncancelar.setBounds(470, 430, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnver_cliente;
    private javax.swing.JButton btnvistas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel etibuscar_cliente;
    private javax.swing.JLabel eticonsulta_Empleado;
    private javax.swing.JLabel etiselecciona_una_opcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtoncodigo;
    private javax.swing.JRadioButton jRadioButtonnumero_de_documento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable panleconsulta_empleado;
    private javax.swing.JTextField txtbuscar_cliente;
    private javax.swing.JTextField txtnumero_de_documento;
    // End of variables declaration//GEN-END:variables
}
