/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Informes;

/**
 *
 * @author jose
 */
public class Consulta_Verificacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Verificacion
     */
    public Consulta_Verificacion() {
        initComponents();
        setSize(801, 516);
        setTitle("Consulta Orden de Trabajo");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eti_selecciona_una_opcion = new javax.swing.JLabel();
        jRadioButtoncodigo = new javax.swing.JRadioButton();
        jRadioButtonnumero_de_documento = new javax.swing.JRadioButton();
        btnver_cliente = new javax.swing.JButton();
        txtnumero_de_documento = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etibuscar_cliente = new javax.swing.JLabel();
        txtbuscar_cliente = new javax.swing.JTextField();
        btnvistas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelconsultas_verificacion = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        eticonsulta_verificacion = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 530));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        eti_selecciona_una_opcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eti_selecciona_una_opcion.setText("Selecciona una opcion:");
        jPanel1.add(eti_selecciona_una_opcion);
        eti_selecciona_una_opcion.setBounds(20, 20, 140, 15);

        jRadioButtoncodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtoncodigo.setText("Codigo");
        jRadioButtoncodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoncodigoActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtoncodigo);
        jRadioButtoncodigo.setBounds(20, 50, 70, 23);

        jRadioButtonnumero_de_documento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonnumero_de_documento.setText("Numero de Documento");
        jRadioButtonnumero_de_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonnumero_de_documentoActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonnumero_de_documento);
        jRadioButtonnumero_de_documento.setBounds(200, 50, 160, 23);

        btnver_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnver_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/repo.png"))); // NOI18N
        btnver_cliente.setText("Ver Registro");
        jPanel1.add(btnver_cliente);
        btnver_cliente.setBounds(610, 120, 129, 30);
        jPanel1.add(txtnumero_de_documento);
        txtnumero_de_documento.setBounds(200, 80, 180, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 80, 180, 20);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/0025-search.gif"))); // NOI18N
        jButton1.setText("Buscar");
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 120, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 760, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        etibuscar_cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etibuscar_cliente.setText("Buscar Cliente:");
        jPanel2.add(etibuscar_cliente);
        etibuscar_cliente.setBounds(23, 21, 90, 15);
        jPanel2.add(txtbuscar_cliente);
        txtbuscar_cliente.setBounds(120, 20, 440, 20);

        btnvistas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/netbeans-ide-icono-8962-32.png"))); // NOI18N
        btnvistas.setText("Vista");
        jPanel2.add(btnvistas);
        btnvistas.setBounds(570, 20, 100, 30);

        panelconsultas_verificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Verificaion", "Fecha ", "Cliente", "Servicio", "Placa", "Marca"
            }
        ));
        jScrollPane1.setViewportView(panelconsultas_verificacion);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 690, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 220, 760, 180);

        btnagregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/agregar.gif"))); // NOI18N
        btnagregar.setText("Agregar");
        getContentPane().add(btnagregar);
        btnagregar.setBounds(170, 440, 110, 29);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/dibujo-a-lapiz-modificar-escribir-icono-8118-32.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        getContentPane().add(btnmodificar);
        btnmodificar.setBounds(290, 440, 117, 30);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancelar-icono-4624-32.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar);
        btncancelar.setBounds(420, 440, 119, 30);

        eticonsulta_verificacion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        eticonsulta_verificacion.setText("Consulta Verificacion");
        getContentPane().add(eticonsulta_verificacion);
        eticonsulta_verificacion.setBounds(250, 0, 240, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtoncodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoncodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtoncodigoActionPerformed

    private void jRadioButtonnumero_de_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonnumero_de_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonnumero_de_documentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnver_cliente;
    private javax.swing.JButton btnvistas;
    private javax.swing.JLabel eti_selecciona_una_opcion;
    private javax.swing.JLabel etibuscar_cliente;
    private javax.swing.JLabel eticonsulta_verificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtoncodigo;
    private javax.swing.JRadioButton jRadioButtonnumero_de_documento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable panelconsultas_verificacion;
    private javax.swing.JTextField txtbuscar_cliente;
    private javax.swing.JTextField txtnumero_de_documento;
    // End of variables declaration//GEN-END:variables
}
