/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

/**
 *
 * @author HOME
 */
public class Agenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        setTitle("Agenda");
        setSize(796, 551);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etiCI = new javax.swing.JLabel();
        etinombre = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        calendariofechafinal = new com.toedter.calendar.JDateChooser();
        etifechafinal = new javax.swing.JLabel();
        etifechadeinicio = new javax.swing.JLabel();
        calendariofechadeinicio = new com.toedter.calendar.JDateChooser();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        etiapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        etidireccion = new javax.swing.JLabel();
        etitelefono = new javax.swing.JLabel();
        etiemail = new javax.swing.JLabel();
        eticompania = new javax.swing.JLabel();
        txtcompania = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        etiusuario = new javax.swing.JLabel();
        combousuario = new javax.swing.JComboBox();
        etiobservacion = new javax.swing.JLabel();
        txtobservacion = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelagenda = new javax.swing.JTable();
        etiagenda = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 560));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setText("Codigo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(42, 23, 33, 14);

        jLabel3.setText("Niombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(36, 49, 39, 14);

        jLabel4.setText("Direccion");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(32, 75, 43, 14);

        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(33, 101, 42, 14);

        jLabel6.setText("Modelo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(245, 49, 34, 14);

        jLabel7.setText("Chasis");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(44, 124, 31, 14);

        jLabel8.setText("Chapa");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(44, 155, 31, 14);

        jLabel9.setText("Fecha de Inicio");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(235, 23, 72, 14);

        jLabel10.setText("Fecha Final");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(397, 23, 54, 14);

        jLabel11.setText("Marca");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 75, 29, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(85, 20, 72, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(85, 46, 72, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(85, 72, 72, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(85, 98, 72, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(85, 124, 72, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(85, 155, 72, 20);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(297, 46, 28, 20);

        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(297, 72, 28, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(311, 20, 76, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(455, 20, 71, 20);

        jLabel12.setText("Servicio");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 101, 37, 14);

        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(297, 98, 28, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 33, 611, 0);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel3.add(eticodigo);
        eticodigo.setBounds(20, 20, 50, 15);

        etiCI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiCI.setText("CI:");
        jPanel3.add(etiCI);
        etiCI.setBounds(40, 50, 15, 15);

        etinombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etinombre.setText("Nombre:");
        jPanel3.add(etinombre);
        etinombre.setBounds(180, 80, 48, 15);
        jPanel3.add(txtcodigo);
        txtcodigo.setBounds(70, 20, 80, 20);
        jPanel3.add(txtCI);
        txtCI.setBounds(70, 50, 80, 20);

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtnombre);
        txtnombre.setBounds(230, 80, 230, 20);
        jPanel3.add(calendariofechafinal);
        calendariofechafinal.setBounds(510, 10, 95, 20);

        etifechafinal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etifechafinal.setText("Fecha final:");
        jPanel3.add(etifechafinal);
        etifechafinal.setBounds(440, 10, 70, 15);

        etifechadeinicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etifechadeinicio.setText("Fecha de Inicio:");
        jPanel3.add(etifechadeinicio);
        etifechadeinicio.setBounds(240, 10, 90, 15);
        jPanel3.add(calendariofechadeinicio);
        calendariofechadeinicio.setBounds(330, 10, 95, 20);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 110, 90, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel3.add(btnguardar);
        btnguardar.setBounds(10, 140, 90, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(10, 170, 90, 23);

        btneliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar);
        btneliminar.setBounds(10, 200, 90, 23);

        btnsalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnsalir.setText("Salir");
        jPanel3.add(btnsalir);
        btnsalir.setBounds(10, 230, 90, 23);

        etiapellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiapellido.setText("Apellido:");
        jPanel3.add(etiapellido);
        etiapellido.setBounds(180, 110, 50, 15);
        jPanel3.add(txtapellido);
        txtapellido.setBounds(230, 110, 230, 20);

        etidireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidireccion.setText("Direccion:");
        jPanel3.add(etidireccion);
        etidireccion.setBounds(170, 170, 55, 15);

        etitelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitelefono.setText("Telefono:");
        jPanel3.add(etitelefono);
        etitelefono.setBounds(170, 200, 51, 15);

        etiemail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiemail.setText("Email:");
        jPanel3.add(etiemail);
        etiemail.setBounds(180, 230, 35, 15);

        eticompania.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticompania.setText("Compania:");
        jPanel3.add(eticompania);
        eticompania.setBounds(170, 140, 70, 14);
        jPanel3.add(txtcompania);
        txtcompania.setBounds(230, 140, 230, 20);
        jPanel3.add(txtdireccion);
        txtdireccion.setBounds(230, 170, 230, 20);
        jPanel3.add(txttelefono);
        txttelefono.setBounds(230, 200, 230, 20);
        jPanel3.add(txtemail);
        txtemail.setBounds(230, 230, 230, 20);

        etiusuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiusuario.setText("Usuario:");
        jPanel3.add(etiusuario);
        etiusuario.setBounds(460, 40, 47, 15);

        jPanel3.add(combousuario);
        combousuario.setBounds(510, 40, 70, 20);

        etiobservacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiobservacion.setText("Observacion:");
        jPanel3.add(etiobservacion);
        etiobservacion.setBounds(520, 70, 80, 20);

        txtobservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobservacionActionPerformed(evt);
            }
        });
        jPanel3.add(txtobservacion);
        txtobservacion.setBounds(470, 90, 230, 190);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(10, 260, 90, 23);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Estado:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(270, 40, 50, 15);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendiente", "Trabajando", "Postergado", "Terminada" }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(330, 40, 90, 20);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(70, 80, 80, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Turno");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 80, 40, 15);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 40, 710, 290);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelagenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CI", "Nombre", "Apellido", "Telefono", "Dreccion", "Email", "Fecha Inicio", "Fecha final", "Usuario"
            }
        ));
        jScrollPane1.setViewportView(panelagenda);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 680, 150);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 340, 700, 170);

        etiagenda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiagenda.setText("Agenda");
        getContentPane().add(etiagenda);
        etiagenda.setBounds(310, 10, 100, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtobservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private com.toedter.calendar.JDateChooser calendariofechadeinicio;
    private com.toedter.calendar.JDateChooser calendariofechafinal;
    private javax.swing.JComboBox combousuario;
    private javax.swing.JLabel etiCI;
    private javax.swing.JLabel etiagenda;
    private javax.swing.JLabel etiapellido;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel eticompania;
    private javax.swing.JLabel etidireccion;
    private javax.swing.JLabel etiemail;
    private javax.swing.JLabel etifechadeinicio;
    private javax.swing.JLabel etifechafinal;
    private javax.swing.JLabel etinombre;
    private javax.swing.JLabel etiobservacion;
    private javax.swing.JLabel etitelefono;
    private javax.swing.JLabel etiusuario;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable panelagenda;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcompania;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtobservacion;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
