/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

/**
 *
 * @author HOME
 */
public class Boleta_de_Pago extends javax.swing.JInternalFrame {

    /**
     * Creates new form FACTURACION
     */
    public Boleta_de_Pago() {
        initComponents();
        setSize(730,540);
        setTitle("Boleta de Pago");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etiCI = new javax.swing.JLabel();
        etieempleado = new javax.swing.JLabel();
        eticliente = new javax.swing.JLabel();
        itemorden = new javax.swing.JLabel();
        eticodigodeservicio = new javax.swing.JLabel();
        eticantidad = new javax.swing.JLabel();
        etipreciounitario = new javax.swing.JLabel();
        etiservicio = new javax.swing.JLabel();
        comboempleado = new javax.swing.JComboBox();
        txtcodigo = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtorden = new javax.swing.JTextField();
        txtcodigodeservicio = new javax.swing.JTextField();
        txtservicio = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtpreciounitario = new javax.swing.JTextField();
        etiruc = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        etifecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelfacturacion = new javax.swing.JTable();
        etitotalIVA = new javax.swing.JLabel();
        txtsubtotales = new javax.swing.JTextField();
        etisubtotales = new javax.swing.JLabel();
        txttotalIVA = new javax.swing.JTextField();
        etitotalgeneral = new javax.swing.JLabel();
        txttotalgeneral = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtnumerodefactura = new javax.swing.JTextField();
        etinumerodefactura = new javax.swing.JLabel();
        calendariofecha = new com.toedter.calendar.JDateChooser();
        etiboletadepago = new javax.swing.JLabel();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(740, 550));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(16, 28, 50, 20);

        etiCI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiCI.setText("CI:");
        jPanel1.add(etiCI);
        etiCI.setBounds(20, 50, 40, 20);

        etieempleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etieempleado.setText("Empleado:");
        jPanel1.add(etieempleado);
        etieempleado.setBounds(20, 120, 60, 20);

        eticliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticliente.setText("Cliente:");
        jPanel1.add(eticliente);
        eticliente.setBounds(20, 80, 50, 20);

        itemorden.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemorden.setText("Orden:");
        jPanel1.add(itemorden);
        itemorden.setBounds(460, 20, 50, 20);

        eticodigodeservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigodeservicio.setText("Codigo de Servicio:");
        jPanel1.add(eticodigodeservicio);
        eticodigodeservicio.setBounds(20, 170, 110, 20);

        eticantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticantidad.setText("Cantidad:");
        jPanel1.add(eticantidad);
        eticantidad.setBounds(320, 170, 60, 20);

        etipreciounitario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etipreciounitario.setText("Precio Unitario:");
        jPanel1.add(etipreciounitario);
        etipreciounitario.setBounds(430, 170, 90, 20);

        etiservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiservicio.setText("Servicio:");
        jPanel1.add(etiservicio);
        etiservicio.setBounds(180, 170, 50, 20);

        comboempleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Juan Carlos", "Rodrigo Gonzalez", "Pedro Benitez", "Raul pintos" }));
        jPanel1.add(comboempleado);
        comboempleado.setBounds(100, 120, 100, 20);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(70, 30, 90, 20);
        jPanel1.add(txtCI);
        txtCI.setBounds(70, 60, 90, 20);
        jPanel1.add(txtcliente);
        txtcliente.setBounds(70, 90, 300, 20);

        txtorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtordenActionPerformed(evt);
            }
        });
        jPanel1.add(txtorden);
        txtorden.setBounds(510, 20, 80, 20);
        jPanel1.add(txtcodigodeservicio);
        txtcodigodeservicio.setBounds(130, 170, 40, 20);
        jPanel1.add(txtservicio);
        txtservicio.setBounds(230, 170, 80, 20);
        jPanel1.add(txtcantidad);
        txtcantidad.setBounds(380, 170, 40, 20);
        jPanel1.add(txtpreciounitario);
        txtpreciounitario.setBounds(520, 170, 60, 20);

        etiruc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiruc.setText("Ruc:");
        jPanel1.add(etiruc);
        etiruc.setBounds(230, 20, 30, 15);
        jPanel1.add(txtruc);
        txtruc.setBounds(270, 20, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 640, 210);

        etifecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etifecha.setText("Fecha:");
        getContentPane().add(etifecha);
        etifecha.setBounds(350, 30, 40, 15);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelfacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Unitario", "Importe", "Iva 5%", "Iva 10%"
            }
        ));
        jScrollPane1.setViewportView(panelfacturacion);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 620, 110);

        etitotalIVA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitotalIVA.setText("Total Iva:");
        jPanel2.add(etitotalIVA);
        etitotalIVA.setBounds(250, 130, 50, 20);
        jPanel2.add(txtsubtotales);
        txtsubtotales.setBounds(130, 130, 70, 20);

        etisubtotales.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etisubtotales.setText("SubTotales:");
        jPanel2.add(etisubtotales);
        etisubtotales.setBounds(60, 130, 80, 20);
        jPanel2.add(txttotalIVA);
        txttotalIVA.setBounds(310, 130, 70, 20);

        etitotalgeneral.setText("Total General");
        jPanel2.add(etitotalgeneral);
        etitotalgeneral.setBounds(440, 130, 70, 20);
        jPanel2.add(txttotalgeneral);
        txttotalgeneral.setBounds(520, 130, 80, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 270, 660, 160);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(10, 10, 80, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel3.add(btnguardar);
        btnguardar.setBounds(100, 10, 80, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(190, 10, 90, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(290, 10, 90, 23);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Vista");
        jPanel3.add(jButton1);
        jButton1.setBounds(390, 10, 80, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(90, 440, 510, 60);
        getContentPane().add(txtnumerodefactura);
        txtnumerodefactura.setBounds(610, 30, 90, 20);

        etinumerodefactura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etinumerodefactura.setText("Numero de Factura:");
        getContentPane().add(etinumerodefactura);
        etinumerodefactura.setBounds(500, 30, 110, 15);
        getContentPane().add(calendariofecha);
        calendariofecha.setBounds(400, 30, 95, 20);

        etiboletadepago.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiboletadepago.setText("Boleta de Pago");
        getContentPane().add(etiboletadepago);
        etiboletadepago.setBounds(160, 20, 180, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtordenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtordenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private com.toedter.calendar.JDateChooser calendariofecha;
    private javax.swing.JComboBox comboempleado;
    private javax.swing.JLabel etiCI;
    private javax.swing.JLabel etiboletadepago;
    private javax.swing.JLabel eticantidad;
    private javax.swing.JLabel eticliente;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel eticodigodeservicio;
    private javax.swing.JLabel etieempleado;
    private javax.swing.JLabel etifecha;
    private javax.swing.JLabel etinumerodefactura;
    private javax.swing.JLabel etipreciounitario;
    private javax.swing.JLabel etiruc;
    private javax.swing.JLabel etiservicio;
    private javax.swing.JLabel etisubtotales;
    private javax.swing.JLabel etitotalIVA;
    private javax.swing.JLabel etitotalgeneral;
    private javax.swing.JLabel itemorden;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelfacturacion;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigodeservicio;
    private javax.swing.JTextField txtnumerodefactura;
    private javax.swing.JTextField txtorden;
    private javax.swing.JTextField txtpreciounitario;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txtservicio;
    private javax.swing.JTextField txtsubtotales;
    private javax.swing.JTextField txttotalIVA;
    private javax.swing.JTextField txttotalgeneral;
    // End of variables declaration//GEN-END:variables
}
