/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

/**
 *
 * @author jose
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public Login() {
       getContentPane().setBackground(new java.awt.Color(0,139,139));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiserviciosmecanicos = new javax.swing.JLabel();
        etiusuario = new javax.swing.JLabel();
        eticontrasena = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        btnentrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().setLayout(null);

        etiserviciosmecanicos.setBackground(new java.awt.Color(153, 0, 0));
        etiserviciosmecanicos.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        etiserviciosmecanicos.setText("SERVICIOS MECANICOS ACE SAC");
        getContentPane().add(etiserviciosmecanicos);
        etiserviciosmecanicos.setBounds(10, 30, 600, 43);

        etiusuario.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        etiusuario.setText("Usuario:");
        getContentPane().add(etiusuario);
        etiusuario.setBounds(70, 150, 100, 29);

        eticontrasena.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        eticontrasena.setText("Contraseña:");
        getContentPane().add(eticontrasena);
        eticontrasena.setBounds(30, 220, 140, 29);
        getContentPane().add(txtusuario);
        txtusuario.setBounds(180, 160, 190, 20);
        getContentPane().add(Password);
        Password.setBounds(180, 220, 190, 20);

        btnentrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnentrar.setText("Entrar");
        getContentPane().add(btnentrar);
        btnentrar.setBounds(240, 260, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel eticontrasena;
    private javax.swing.JLabel etiserviciosmecanicos;
    private javax.swing.JLabel etiusuario;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
