/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

/**
 *
 * @author HOME
 */
public class Orden_de_trabajo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Orden_de_trabajo
     */
    public Orden_de_trabajo() {
        initComponents();
        setTitle("Orden de Trabajo");
        setSize(800, 400);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        itemcodigo = new javax.swing.JLabel();
        itemcliente = new javax.swing.JLabel();
        itemCI = new javax.swing.JLabel();
        itemempleado = new javax.swing.JLabel();
        itemnumerodepresupuesto = new javax.swing.JLabel();
        comboempleado = new javax.swing.JComboBox();
        itemcodigodeservicio = new javax.swing.JLabel();
        itemdescripciondelservicio = new javax.swing.JLabel();
        itemcantidad = new javax.swing.JLabel();
        txtcodigodeservicio = new javax.swing.JTextField();
        txtdescripciondelservicio = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtnumerodepresupuesto = new javax.swing.JTextField();
        itemestado = new javax.swing.JLabel();
        comboestado = new javax.swing.JComboBox();
        itemfechadeorden = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelordendetrabajo = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnfacturacion = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        calendariofechadeorden = new com.toedter.calendar.JDateChooser();
        etiordendetrabajo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(790, 450));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ORDEN DE TRABAJO"));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.setLayout(null);

        itemcodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemcodigo.setText("Codigo:");
        jPanel1.add(itemcodigo);
        itemcodigo.setBounds(20, 20, 43, 15);

        itemcliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemcliente.setText("Cliente:");
        jPanel1.add(itemcliente);
        itemcliente.setBounds(190, 20, 42, 15);

        itemCI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemCI.setText("CI:");
        jPanel1.add(itemCI);
        itemCI.setBounds(50, 50, 20, 15);

        itemempleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemempleado.setText("Empleado:");
        jPanel1.add(itemempleado);
        itemempleado.setBounds(590, 80, 60, 15);

        itemnumerodepresupuesto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemnumerodepresupuesto.setText("Numero de Presupuesto:");
        jPanel1.add(itemnumerodepresupuesto);
        itemnumerodepresupuesto.setBounds(540, 10, 140, 15);

        comboempleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Juan carlos", "Roberto gonzalez", "Raul Amarilla", "Carlos Gimenez" }));
        jPanel1.add(comboempleado);
        comboempleado.setBounds(650, 80, 80, 20);

        itemcodigodeservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemcodigodeservicio.setText("Codigo Servicio:");
        jPanel1.add(itemcodigodeservicio);
        itemcodigodeservicio.setBounds(50, 100, 100, 15);

        itemdescripciondelservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemdescripciondelservicio.setText("Descripcion del Servicio:");
        jPanel1.add(itemdescripciondelservicio);
        itemdescripciondelservicio.setBounds(230, 90, 140, 20);

        itemcantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemcantidad.setText("Cantidad:");
        jPanel1.add(itemcantidad);
        itemcantidad.setBounds(470, 100, 60, 15);
        jPanel1.add(txtcodigodeservicio);
        txtcodigodeservicio.setBounds(60, 120, 90, 20);
        jPanel1.add(txtdescripciondelservicio);
        txtdescripciondelservicio.setBounds(210, 120, 200, 20);
        jPanel1.add(txtcantidad);
        txtcantidad.setBounds(470, 120, 60, 20);
        jPanel1.add(txtCI);
        txtCI.setBounds(70, 50, 70, 20);

        txtcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtcliente);
        txtcliente.setBounds(240, 20, 280, 20);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(70, 20, 70, 20);
        jPanel1.add(txtnumerodepresupuesto);
        txtnumerodepresupuesto.setBounds(680, 10, 60, 20);

        itemestado.setText("Estado:");
        jPanel1.add(itemestado);
        itemestado.setBounds(610, 110, 37, 14);

        comboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terminado", "Trabajando", "En Espera de repuestos" }));
        jPanel1.add(comboestado);
        comboestado.setBounds(650, 110, 80, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 750, 160);

        itemfechadeorden.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemfechadeorden.setText("Fecha de orden:");
        getContentPane().add(itemfechadeorden);
        itemfechadeorden.setBounds(570, 20, 90, 15);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        panelordendetrabajo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelordendetrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(panelordendetrabajo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 628, 91);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel2.add(btnnuevo);
        btnnuevo.setBounds(170, 120, 70, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel2.add(btnguardar);
        btnguardar.setBounds(260, 120, 80, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel2.add(btnmodificar);
        btnmodificar.setBounds(350, 120, 90, 23);

        btnfacturacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnfacturacion.setText("Boleta de pago");
        btnfacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnfacturacion);
        btnfacturacion.setBounds(20, 120, 130, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel2.add(btncancelar);
        btncancelar.setBounds(450, 120, 83, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel2.add(btnvista);
        btnvista.setBounds(550, 120, 59, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 210, 710, 150);
        getContentPane().add(calendariofechadeorden);
        calendariofechadeorden.setBounds(660, 20, 95, 20);

        etiordendetrabajo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiordendetrabajo.setText("Orden de Trabajo");
        getContentPane().add(etiordendetrabajo);
        etiordendetrabajo.setBounds(230, 10, 210, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclienteActionPerformed

    private void btnfacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfacturacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnfacturacion;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnvista;
    private com.toedter.calendar.JDateChooser calendariofechadeorden;
    private javax.swing.JComboBox comboempleado;
    private javax.swing.JComboBox comboestado;
    private javax.swing.JLabel etiordendetrabajo;
    private javax.swing.JLabel itemCI;
    private javax.swing.JLabel itemcantidad;
    private javax.swing.JLabel itemcliente;
    private javax.swing.JLabel itemcodigo;
    private javax.swing.JLabel itemcodigodeservicio;
    private javax.swing.JLabel itemdescripciondelservicio;
    private javax.swing.JLabel itemempleado;
    private javax.swing.JLabel itemestado;
    private javax.swing.JLabel itemfechadeorden;
    private javax.swing.JLabel itemnumerodepresupuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelordendetrabajo;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigodeservicio;
    private javax.swing.JTextField txtdescripciondelservicio;
    private javax.swing.JTextField txtnumerodepresupuesto;
    // End of variables declaration//GEN-END:variables
}
