/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

/**
 *
 * @author HOME
 */
public class Presupuesto extends javax.swing.JInternalFrame {

    /**
     * Creates new form SERVICIO
     */
    public Presupuesto() {
        initComponents();
        setTitle("Presupuesto");
        setSize(710, 430);
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        eticliente = new javax.swing.JLabel();
        etiCI = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        etidescripcion = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        eticantidad = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        eticodigodeservicio = new javax.swing.JLabel();
        txtcodigodeservicio = new javax.swing.JTextField();
        etiimporte = new javax.swing.JLabel();
        txtimporte = new javax.swing.JTextField();
        etiingreso = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        etiusuario = new javax.swing.JLabel();
        combousuario = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelpresupuesto = new javax.swing.JTable();
        etitotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnordendetrabajo = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        etifecha = new javax.swing.JLabel();
        calendariofecha = new com.toedter.calendar.JDateChooser();
        etipresupuesto = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Presupuesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel2.add(eticodigo);
        eticodigo.setBounds(50, 20, 50, 15);
        jPanel2.add(txtcodigo);
        txtcodigo.setBounds(100, 20, 80, 20);

        eticliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticliente.setText("Cliente:");
        jPanel2.add(eticliente);
        eticliente.setBounds(220, 30, 50, 15);

        etiCI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiCI.setText("CI:");
        jPanel2.add(etiCI);
        etiCI.setBounds(60, 50, 30, 15);

        txtCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIActionPerformed(evt);
            }
        });
        jPanel2.add(txtCI);
        txtCI.setBounds(100, 50, 80, 20);
        jPanel2.add(txtcliente);
        txtcliente.setBounds(270, 30, 210, 20);

        etidescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etidescripcion.setText("Descrpcion:");
        jPanel2.add(etidescripcion);
        etidescripcion.setBounds(200, 80, 70, 20);
        jPanel2.add(txtdescripcion);
        txtdescripcion.setBounds(140, 110, 190, 20);

        eticantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticantidad.setText("Cantidad:");
        jPanel2.add(eticantidad);
        eticantidad.setBounds(370, 80, 60, 20);

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtcantidad);
        txtcantidad.setBounds(370, 110, 50, 20);

        eticodigodeservicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigodeservicio.setText("Codigo de Servicio:");
        jPanel2.add(eticodigodeservicio);
        eticodigodeservicio.setBounds(10, 80, 110, 15);

        txtcodigodeservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigodeservicioActionPerformed(evt);
            }
        });
        jPanel2.add(txtcodigodeservicio);
        txtcodigodeservicio.setBounds(30, 110, 80, 20);

        etiimporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiimporte.setText("Importe:");
        jPanel2.add(etiimporte);
        etiimporte.setBounds(480, 80, 60, 20);
        jPanel2.add(txtimporte);
        txtimporte.setBounds(470, 110, 70, 20);

        etiingreso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiingreso.setText("Nº de Ingreso:");
        jPanel2.add(etiingreso);
        etiingreso.setBounds(490, 20, 80, 15);
        jPanel2.add(txtingreso);
        txtingreso.setBounds(570, 20, 70, 20);

        etiusuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiusuario.setText("Usuario:");
        jPanel2.add(etiusuario);
        etiusuario.setBounds(520, 140, 50, 15);

        combousuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Juan", "Jose", "Pedro" }));
        combousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combousuarioActionPerformed(evt);
            }
        });
        jPanel2.add(combousuario);
        combousuario.setBounds(580, 140, 80, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 29, 680, 170);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        panelpresupuesto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        panelpresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Importe "
            }
        ));
        jScrollPane1.setViewportView(panelpresupuesto);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 20, 500, 87);

        etitotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etitotal.setText("Total:");
        jPanel1.add(etitotal);
        etitotal.setBounds(410, 110, 30, 20);
        jPanel1.add(txttotal);
        txttotal.setBounds(440, 110, 100, 20);

        btnordendetrabajo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnordendetrabajo.setText("Orden de Trabajo");
        jPanel1.add(btnordendetrabajo);
        btnordendetrabajo.setBounds(40, 110, 140, 23);

        btnsalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir);
        btnsalir.setBounds(320, 150, 60, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel1.add(btnmodificar);
        btnmodificar.setBounds(220, 150, 90, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel1.add(btnguardar);
        btnguardar.setBounds(130, 150, 80, 23);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel1.add(btnnuevo);
        btnnuevo.setBounds(50, 150, 70, 23);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 150, 83, 23);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Vista");
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 150, 59, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 210, 570, 180);

        etifecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etifecha.setText("Fecha:");
        getContentPane().add(etifecha);
        etifecha.setBounds(490, 10, 40, 20);
        getContentPane().add(calendariofecha);
        calendariofecha.setBounds(540, 10, 95, 20);

        etipresupuesto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etipresupuesto.setText("Presupuesto");
        getContentPane().add(etipresupuesto);
        etipresupuesto.setBounds(230, 0, 170, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtcodigodeservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigodeservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigodeservicioActionPerformed

    private void combousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combousuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnordendetrabajo;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser calendariofecha;
    private javax.swing.JComboBox combousuario;
    private javax.swing.JLabel etiCI;
    private javax.swing.JLabel eticantidad;
    private javax.swing.JLabel eticliente;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel eticodigodeservicio;
    private javax.swing.JLabel etidescripcion;
    private javax.swing.JLabel etifecha;
    private javax.swing.JLabel etiimporte;
    private javax.swing.JLabel etiingreso;
    private javax.swing.JLabel etipresupuesto;
    private javax.swing.JLabel etitotal;
    private javax.swing.JLabel etiusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelpresupuesto;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigodeservicio;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtimporte;
    private javax.swing.JTextField txtingreso;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
