/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

/**
 *
 * @author jose
 */
public class Recepcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Recepcion
     */
    public Recepcion() {
        
        initComponents();
        setSize(830, 560);
        setTitle("Recepcion");
        setClosable(true);
        setIconifiable(true);
        setResizable(false);
        setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eticodigo = new javax.swing.JLabel();
        etifecha = new javax.swing.JLabel();
        etiturno = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtturno = new javax.swing.JTextField();
        calendariofecha = new com.toedter.calendar.JDateChooser();
        btnprimero = new javax.swing.JButton();
        btnultimo = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        btnanterior = new javax.swing.JButton();
        etiusuario = new javax.swing.JLabel();
        combousuario = new javax.swing.JComboBox();
        btnNuevoR = new javax.swing.JButton();
        btnguardarR = new javax.swing.JButton();
        btnmodificarR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btncancelarR = new javax.swing.JButton();
        btnvistaR = new javax.swing.JButton();
        panelvehiculo = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        eticodigooo = new javax.swing.JLabel();
        etichasis = new javax.swing.JLabel();
        etiplaca = new javax.swing.JLabel();
        etimarca = new javax.swing.JLabel();
        etimodelo = new javax.swing.JLabel();
        eticliente = new javax.swing.JLabel();
        txtcodigooo = new javax.swing.JTextField();
        txtchasis = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        combomarca = new javax.swing.JComboBox();
        combomodelo = new javax.swing.JComboBox();
        txtcliente = new javax.swing.JTextField();
        btnNuevov = new javax.swing.JButton();
        btnguardarv = new javax.swing.JButton();
        btnmodificarv = new javax.swing.JButton();
        btnsalirv = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        eticodigoo = new javax.swing.JLabel();
        etiCI = new javax.swing.JLabel();
        etinombre = new javax.swing.JLabel();
        etiapellido = new javax.swing.JLabel();
        eticompania = new javax.swing.JLabel();
        txtcodigoo = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcompania = new javax.swing.JTextField();
        btnnuevoC = new javax.swing.JButton();
        btnguardarC = new javax.swing.JButton();
        btnmodificarC = new javax.swing.JButton();
        btnsalirC = new javax.swing.JButton();
        btncancelarC = new javax.swing.JButton();
        btnvistaC = new javax.swing.JButton();
        etirecepcion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recepcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.black)); // NOI18N
        jPanel1.setLayout(null);

        eticodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(30, 20, 50, 15);

        etifecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etifecha.setText("Fecha:");
        jPanel1.add(etifecha);
        etifecha.setBounds(240, 20, 40, 15);

        etiturno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiturno.setText("Turno:");
        jPanel1.add(etiturno);
        etiturno.setBounds(570, 10, 40, 15);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(80, 20, 80, 20);
        jPanel1.add(txtturno);
        txtturno.setBounds(610, 10, 60, 20);
        jPanel1.add(calendariofecha);
        calendariofecha.setBounds(280, 20, 95, 20);

        btnprimero.setText("<<");
        jPanel1.add(btnprimero);
        btnprimero.setBounds(610, 40, 50, 23);

        btnultimo.setText(">>");
        jPanel1.add(btnultimo);
        btnultimo.setBounds(660, 40, 50, 23);

        btnsiguiente.setText(">");
        jPanel1.add(btnsiguiente);
        btnsiguiente.setBounds(560, 40, 50, 23);

        btnanterior.setText("<");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnanterior);
        btnanterior.setBounds(510, 40, 50, 23);

        etiusuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiusuario.setText("Usuario:");
        jPanel1.add(etiusuario);
        etiusuario.setBounds(30, 50, 50, 15);

        combousuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combousuario);
        combousuario.setBounds(80, 50, 90, 20);

        btnNuevoR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevoR.setText("Nuevo");
        jPanel1.add(btnNuevoR);
        btnNuevoR.setBounds(20, 110, 90, 23);

        btnguardarR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardarR.setText("Guardar");
        jPanel1.add(btnguardarR);
        btnguardarR.setBounds(120, 110, 90, 23);

        btnmodificarR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificarR.setText("Modificar");
        jPanel1.add(btnmodificarR);
        btnmodificarR.setBounds(220, 110, 90, 23);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Observacion:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 70, 80, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(520, 70, 190, 60);

        btncancelarR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelarR.setText("Cancelar");
        jPanel1.add(btncancelarR);
        btncancelarR.setBounds(320, 110, 83, 23);

        btnvistaR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvistaR.setText("Vista");
        jPanel1.add(btnvistaR);
        btnvistaR.setBounds(410, 110, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 720, 140);

        jPanel3.setLayout(null);

        eticodigooo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticodigooo.setText("Codigo:");
        jPanel3.add(eticodigooo);
        eticodigooo.setBounds(10, 20, 43, 15);

        etichasis.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etichasis.setText("Chasis:");
        jPanel3.add(etichasis);
        etichasis.setBounds(210, 110, 43, 20);

        etiplaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiplaca.setText("Placa:");
        jPanel3.add(etiplaca);
        etiplaca.setBounds(220, 140, 34, 20);

        etimarca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etimarca.setText("Marca:");
        jPanel3.add(etimarca);
        etimarca.setBounds(550, 90, 36, 15);

        etimodelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etimodelo.setText("Modelo:");
        jPanel3.add(etimodelo);
        etimodelo.setBounds(550, 120, 43, 15);

        eticliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eticliente.setText("Cliente:");
        jPanel3.add(eticliente);
        eticliente.setBounds(210, 80, 50, 20);
        jPanel3.add(txtcodigooo);
        txtcodigooo.setBounds(60, 20, 70, 20);

        txtchasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchasisActionPerformed(evt);
            }
        });
        jPanel3.add(txtchasis);
        txtchasis.setBounds(260, 110, 250, 20);
        jPanel3.add(txtplaca);
        txtplaca.setBounds(260, 140, 250, 20);

        combomarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combomarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomarcaActionPerformed(evt);
            }
        });
        jPanel3.add(combomarca);
        combomarca.setBounds(600, 90, 100, 20);

        combomodelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(combomodelo);
        combomodelo.setBounds(600, 120, 100, 20);
        jPanel3.add(txtcliente);
        txtcliente.setBounds(260, 80, 250, 20);

        btnNuevov.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevov.setText("Nuevo");
        btnNuevov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevovActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevov);
        btnNuevov.setBounds(10, 50, 90, 23);

        btnguardarv.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardarv.setText("Guardar");
        jPanel3.add(btnguardarv);
        btnguardarv.setBounds(10, 80, 90, 23);

        btnmodificarv.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificarv.setText("Modificar");
        btnmodificarv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarvActionPerformed(evt);
            }
        });
        jPanel3.add(btnmodificarv);
        btnmodificarv.setBounds(10, 110, 90, 23);

        btnsalirv.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnsalirv.setText("Salir");
        jPanel3.add(btnsalirv);
        btnsalirv.setBounds(10, 140, 90, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(10, 170, 90, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel3.add(btnvista);
        btnvista.setBounds(10, 200, 90, 23);

        panelvehiculo.addTab("Vehiculo", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        eticodigoo.setText("Codigo:");
        jPanel2.add(eticodigoo);
        eticodigoo.setBounds(10, 10, 40, 14);

        etiCI.setText("CI:");
        jPanel2.add(etiCI);
        etiCI.setBounds(30, 40, 20, 14);

        etinombre.setText("Nombre:");
        jPanel2.add(etinombre);
        etinombre.setBounds(190, 60, 50, 14);

        etiapellido.setText("Apellido:");
        jPanel2.add(etiapellido);
        etiapellido.setBounds(190, 90, 41, 14);

        eticompania.setText("Compania:");
        jPanel2.add(eticompania);
        eticompania.setBounds(180, 120, 51, 14);
        jPanel2.add(txtcodigoo);
        txtcodigoo.setBounds(50, 10, 60, 20);
        jPanel2.add(txtCI);
        txtCI.setBounds(50, 40, 60, 20);
        jPanel2.add(txtnombre);
        txtnombre.setBounds(240, 60, 270, 20);
        jPanel2.add(txtapellido);
        txtapellido.setBounds(240, 90, 270, 20);
        jPanel2.add(txtcompania);
        txtcompania.setBounds(240, 120, 270, 20);

        btnnuevoC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevoC.setText("Nuevo");
        jPanel2.add(btnnuevoC);
        btnnuevoC.setBounds(20, 80, 90, 23);

        btnguardarC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardarC.setText("Guardar");
        btnguardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarCActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardarC);
        btnguardarC.setBounds(20, 110, 90, 23);

        btnmodificarC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificarC.setText("Modificar");
        jPanel2.add(btnmodificarC);
        btnmodificarC.setBounds(20, 140, 90, 23);

        btnsalirC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnsalirC.setText("Salir");
        jPanel2.add(btnsalirC);
        btnsalirC.setBounds(20, 170, 90, 23);

        btncancelarC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelarC.setText("Cancelar");
        jPanel2.add(btncancelarC);
        btncancelarC.setBounds(20, 200, 90, 23);

        btnvistaC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvistaC.setText("Vista");
        jPanel2.add(btnvistaC);
        btnvistaC.setBounds(20, 230, 90, 23);

        panelvehiculo.addTab("Cliente", jPanel2);

        getContentPane().add(panelvehiculo);
        panelvehiculo.setBounds(50, 210, 730, 290);

        etirecepcion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etirecepcion.setText("Recepcion");
        getContentPane().add(etirecepcion);
        etirecepcion.setBounds(280, 20, 130, 29);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Agenda");
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 190, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void txtchasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchasisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchasisActionPerformed

    private void combomarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomarcaActionPerformed

    private void btnNuevovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevovActionPerformed

    private void btnmodificarvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarvActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnguardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoR;
    private javax.swing.JButton btnNuevov;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelarC;
    private javax.swing.JButton btncancelarR;
    private javax.swing.JButton btnguardarC;
    private javax.swing.JButton btnguardarR;
    private javax.swing.JButton btnguardarv;
    private javax.swing.JButton btnmodificarC;
    private javax.swing.JButton btnmodificarR;
    private javax.swing.JButton btnmodificarv;
    private javax.swing.JButton btnnuevoC;
    private javax.swing.JButton btnprimero;
    private javax.swing.JButton btnsalirC;
    private javax.swing.JButton btnsalirv;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnultimo;
    private javax.swing.JButton btnvista;
    private javax.swing.JButton btnvistaC;
    private javax.swing.JButton btnvistaR;
    private com.toedter.calendar.JDateChooser calendariofecha;
    private javax.swing.JComboBox combomarca;
    private javax.swing.JComboBox combomodelo;
    private javax.swing.JComboBox combousuario;
    private javax.swing.JLabel etiCI;
    private javax.swing.JLabel etiapellido;
    private javax.swing.JLabel etichasis;
    private javax.swing.JLabel eticliente;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel eticodigoo;
    private javax.swing.JLabel eticodigooo;
    private javax.swing.JLabel eticompania;
    private javax.swing.JLabel etifecha;
    private javax.swing.JLabel etimarca;
    private javax.swing.JLabel etimodelo;
    private javax.swing.JLabel etinombre;
    private javax.swing.JLabel etiplaca;
    private javax.swing.JLabel etirecepcion;
    private javax.swing.JLabel etiturno;
    private javax.swing.JLabel etiusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane panelvehiculo;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtchasis;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigoo;
    private javax.swing.JTextField txtcodigooo;
    private javax.swing.JTextField txtcompania;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtturno;
    // End of variables declaration//GEN-END:variables
}
