/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_Movimiento;

import java.awt.event.FocusAdapter;

/**
 *
 * @author HOME
 */
public class Verificacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VERIFICACION
     */
    public Verificacion() {
        initComponents();
        setSize(641, 576);
        setTitle("Verificacion");
        setClosable(true);//para poner icono de salir en formulario
        setIconifiable(true);//para poner boton minimizar en formulario
        setResizable(false);//para no poder tocar agrandar o achicar formulario
        setMaximizable(false);//para no permitir maximizar mi formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiplaca = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        eticliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        etiingreso = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        etimarca = new javax.swing.JLabel();
        etimodelo = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        etiobservaciones = new javax.swing.JLabel();
        etiempleado = new javax.swing.JLabel();
        comboempleado = new javax.swing.JComboBox();
        btnbuscar = new javax.swing.JButton();
        eticodigo = new javax.swing.JLabel();
        txtxodigo = new javax.swing.JTextField();
        etiestado = new javax.swing.JLabel();
        comboestado = new javax.swing.JComboBox();
        etiverificacion = new javax.swing.JLabel();
        comboverificacion = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobservaciones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnvista = new javax.swing.JButton();
        etifecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        calendariofecha = new com.toedter.calendar.JDateChooser();
        btnpresupuesto = new javax.swing.JButton();
        etiverificacionTitle = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(689, 723));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Verificacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        etiplaca.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etiplaca.setText("Placa:");
        jPanel1.add(etiplaca);
        etiplaca.setBounds(350, 100, 40, 20);
        jPanel1.add(txtplaca);
        txtplaca.setBounds(390, 100, 91, 20);

        eticliente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        eticliente.setText("Cliente");
        jPanel1.add(eticliente);
        eticliente.setBounds(50, 50, 40, 14);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 70, 0, 0);
        jPanel1.add(txtcliente);
        txtcliente.setBounds(100, 50, 230, 20);

        etiingreso.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etiingreso.setText("Nª de Ingreso");
        jPanel1.add(etiingreso);
        etiingreso.setBounds(310, 10, 80, 20);

        txtingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresoActionPerformed(evt);
            }
        });
        jPanel1.add(txtingreso);
        txtingreso.setBounds(390, 10, 90, 20);

        etimarca.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etimarca.setText("Marca:");
        jPanel1.add(etimarca);
        etimarca.setBounds(350, 70, 40, 20);

        etimodelo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etimodelo.setText("Modelo:");
        jPanel1.add(etimodelo);
        etimodelo.setBounds(340, 40, 50, 20);
        jPanel1.add(txtmarca);
        txtmarca.setBounds(390, 70, 90, 20);

        txtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodeloActionPerformed(evt);
            }
        });
        jPanel1.add(txtmodelo);
        txtmodelo.setBounds(390, 40, 90, 20);

        etiobservaciones.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etiobservaciones.setText("Observaciones del vehiculo:");
        jPanel1.add(etiobservaciones);
        etiobservaciones.setBounds(60, 180, 160, 14);

        etiempleado.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etiempleado.setText("Empleado:");
        jPanel1.add(etiempleado);
        etiempleado.setBounds(260, 160, 70, 14);

        comboempleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboempleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jorge Vairo", "Javier Gandula" }));
        jPanel1.add(comboempleado);
        comboempleado.setBounds(330, 160, 150, 21);

        btnbuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnbuscar.setText("Buscar");
        jPanel1.add(btnbuscar);
        btnbuscar.setBounds(490, 10, 80, 23);

        eticodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eticodigo.setText("Codigo:");
        jPanel1.add(eticodigo);
        eticodigo.setBounds(50, 20, 50, 15);
        jPanel1.add(txtxodigo);
        txtxodigo.setBounds(100, 20, 70, 20);

        etiestado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etiestado.setText("Estado:");
        jPanel1.add(etiestado);
        etiestado.setBounds(270, 130, 50, 15);

        comboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendiente", "Anulado", "Aprovado" }));
        jPanel1.add(comboestado);
        comboestado.setBounds(330, 130, 150, 20);

        etiverificacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etiverificacion.setText("Verificacion:");
        jPanel1.add(etiverificacion);
        etiverificacion.setBounds(40, 130, 80, 15);

        comboverificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Verificacion", "Presupuesto", "Reanudar" }));
        jPanel1.add(comboverificacion);
        comboverificacion.setBounds(120, 130, 120, 20);

        txtobservaciones.setColumns(20);
        txtobservaciones.setRows(5);
        jScrollPane2.setViewportView(txtobservaciones);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 210, 550, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 590, 300);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Vehiculo", "Marca", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(2, 2, 510, 98);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 183, 0, 0);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        jPanel3.add(btnnuevo);
        btnnuevo.setBounds(20, 10, 70, 23);

        btnguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        jPanel3.add(btnguardar);
        btnguardar.setBounds(100, 10, 100, 23);

        btnmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(220, 10, 90, 23);

        btncancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel3.add(btncancelar);
        btncancelar.setBounds(330, 10, 83, 23);

        btnvista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnvista.setText("Vista");
        jPanel3.add(btnvista);
        btnvista.setBounds(440, 10, 80, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 480, 580, 50);

        etifecha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        etifecha.setText("Fecha");
        getContentPane().add(etifecha);
        etifecha.setBounds(400, 0, 32, 20);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de verificaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N
        jPanel4.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de Verificacion", "Placa", "Modelo", "Fecha", "Cliente"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 570, 100);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 320, 590, 130);
        getContentPane().add(calendariofecha);
        calendariofecha.setBounds(440, 0, 95, 20);

        btnpresupuesto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnpresupuesto.setText("Presupuesto");
        getContentPane().add(btnpresupuesto);
        btnpresupuesto.setBounds(10, 450, 110, 23);

        etiverificacionTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etiverificacionTitle.setText("Verificacion");
        getContentPane().add(etiverificacionTitle);
        etiverificacionTitle.setBounds(190, 0, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodeloActionPerformed

    private void txtingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingresoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnpresupuesto;
    private javax.swing.JButton btnvista;
    private com.toedter.calendar.JDateChooser calendariofecha;
    private javax.swing.JComboBox comboempleado;
    private javax.swing.JComboBox comboestado;
    private javax.swing.JComboBox comboverificacion;
    private javax.swing.JLabel eticliente;
    private javax.swing.JLabel eticodigo;
    private javax.swing.JLabel etiempleado;
    private javax.swing.JLabel etiestado;
    private javax.swing.JLabel etifecha;
    private javax.swing.JLabel etiingreso;
    private javax.swing.JLabel etimarca;
    private javax.swing.JLabel etimodelo;
    private javax.swing.JLabel etiobservaciones;
    private javax.swing.JLabel etiplaca;
    private javax.swing.JLabel etiverificacion;
    private javax.swing.JLabel etiverificacionTitle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtingreso;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextArea txtobservaciones;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtxodigo;
    // End of variables declaration//GEN-END:variables
}
